---
version: '0.1.{build}'
assembly_info:
    patch: true
    file: MyVersion.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

configuration: Release
before_build:
    - nuget restore
build:
    parallel: true
    project: OWRankTracker.sln

artifacts:
    - path: OWRankTracker\bin\$(configuration)
      type: zip
      name: compiled_package

deploy:
    - provider:  GitHub
      auth_token:
          secure: 
      artifact: OWRankTracker\bin\Release
      name: compiled_package
      on:
          branch: master
          appveyor_repo_tag: true

