---
image: Visual Studio 2017
version: '0.1.{build}'
assembly_info:
    patch: true
    file: MyVersion.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

configuration: Release
before_build:
        - cmd: nuget restore
        - ps: >-
            # If APPVEYOR_REPO_TAG_NAME is set, this is a tagged release
            if ($env:APPVEYOR_REPO_TAG_NAME -eq "true") {
                ${env:ZIP_ARTIFACT_NAME} = "OWRankTracker-$env:APPVEYOR_REPO_TAG_NAME.zip";
                ${env:MSI_ARTIFACT_NAME} = "OWRankTracker-$env:APPVEYOR_REPO_TAG_NAME.msi";
            } else {
                ${env:ZIP_ARTIFACT_NAME} = "OWRankTracker-build-$env:APPVEYOR_BUILD_VERSION.zip";
                ${env:MSI_ARTIFACT_NAME} = "OWRankTracker-build-$env:APPVEYOR_BUILD_VERSION.msi";
            }
            
build:
    parallel: true
    project: OWRankTracker.sln
    verbosity: minimal

test:
    assemblies:
        only:
            - OWRankTracker.Test\bin\$(configuration)\OWRankTracker.Test.dll
            - OWRankTracker.Core.Test\bin\$(Configuration)\OWRankTracker.Core.Test.dll

artifacts:
    - path: OWRankTracker\bin\$(configuration)
      name: $(ZIP_ARTIFACT_NAME)

    - path:  OWRankTracker.Installer\bin\$(configuration)\OverwatchRankTracker.msi
      name: $(MSI_ARTIFACT_NAME)

before_deploy:
    - ps: >-
        ${env:release_description} = (Get-Content "./ReleaseNotes/${env:APPVEYOR_REPO_TAG_NAME}.txt") -join "`n";

deploy:
    - provider:  GitHub
      auth_token:
          secure: RM5VRaDPrGHUmXhx2H9fF75MzpjeeCsTiSdDA8geFD3fFWz9JawwezptRY+eeQsX
      artifact: 
        - $(ZIP_ARTIFACT_NAME)
        - $(MSI_ARTIFACT_NAME)
      description: $(release_description)
      on:
          appveyor_repo_tag: true

