---
image: Visual Studio 2017
version: '0.1.{build}'
assembly_info:
    patch: true
    file: MyVersion.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

configuration: Release
before_build:
        - cmd: nuget restore
build:
    parallel: true
    project: OWRankTracker.sln
    verbosity: minimal

test:
    assemblies:
        only:
            - OWRankTracker.Test\bin\$(configuration)\OWRankTracker.Test.dll

artifacts:
    - path: OWRankTracker\bin\$(configuration)
      name: OWRankTracker-$(APPVEYOR_BUILD_VERSION)

before_deploy:
    - ps: >-
        ${env:release_description} = (Get-Content "./ReleaseNotes/${env:APPVEYOR_REPO_TAG_NAME}.txt") - join "`n";

deploy:
    - provider:  GitHub
      auth_token:
          secure: RM5VRaDPrGHUmXhx2H9fF75MzpjeeCsTiSdDA8geFD3fFWz9JawwezptRY+eeQsX
      artifact: OWRankTracker-$(APPVEYOR_BUILD_VERSION)
      description: $(release_description)
      on:
          appveyor_repo_tag: true

